flowchart TD
    A["شروع: محاسبه قیمت نهایی محصول"] --> B["قیمت اولیه محصول"]
    B --> D["اعمال تخفیف توافقی بر قیمت اولیه"]
    B --> E["اعمال تخفیف سایت بر قیمت ثانویه"]

    D --> F{"آیا تخفیف گروهی فعال است؟"}
    E --> F

    F -- بله --> G["تخفیف گروهی - بالاترین اولویت"]
    F -- خیر --> H["اعمال سایر تخفیف‌ها"]

    G --> I["محاسبه قیمت پس از تخفیف (با در نظر گرفتن حداکثر مجاز)"]
    H --> M["بررسی تنظیمات فروش/بیزینس: آیا رکوردی بابت تخفیف ثبت شده است؟"]

    I --> J{"آیا کاربر بازاریاب است؟"}

    M -- بله --> J
    M -- خیر --> N["بررسی تنظیمات فروش: مقادیر پیش فرض"]

    N -- بله --> J
    N -- خیر --> n1["بدون اعمال تخفیف سایت یا توافقی"]

    J -- بله --> K["اعمال محدودیت‌های تخفیف بازاریاب"]
    J -- خیر --> L["اعمال محدودیت‌های تخفیف کاربر عادی"]

    K --> O["محاسبه نهایی قیمت پس از تخفیف"]
    L --> O
    n1 --> O

    O --> P["پایان: قیمت نهایی بیمه"]

    %% Styling
    classDef startEnd fill:#2ecc71,color:white,stroke-width:0;
    classDef process fill:#3498db,color:white,stroke-width:0;
    classDef decision fill:#e74c3c,color:white,stroke-width:0;
    classDef priority fill:#f39c12,color:white,stroke-width:0;

    class A,P startEnd
    class B,D,E,H,I,M,N,K,L,O,n1 process
    class F,J decision
    class G priority