---
config:
  layout: dagre
---
flowchart TD
    A["TEST"] --> B["Automation"]
    A --> H["Usability Testing - Semi-Manual"]
    A --> n1["Manual"]
    A --> n4["Security"]

    B --> C["Performance & Load Testing"]
    B --> G["Chaos & Reliability Testing - Automated"]
    B --> E["Accessibility Testing - Automated"]
    B --> D["Compatibility Testing - Automated"]
    B --> F["Database Testing - Automated"]
    B --> n2["API Testing"]
    B --> n3["UI Testing"]

    style A fill:#f9f,stroke:#333,stroke-width:2px
    style B fill:#bbf,stroke:#333,stroke-width:2px
    style H fill:#ffb,stroke:#333,stroke-width:2px,stroke-dasharray: 0
    style n1 fill:#f9f,stroke:#333,stroke-width:2px
    style n4 fill:#FF6D00,stroke:#333,stroke-width:2px
    style C fill:#bfb,stroke:#333,stroke-width:2px
    style G fill:#aaf,stroke:#333,stroke-width:2px
    style E fill:#aff,stroke:#333,stroke-width:2px
    style D fill:#fbb,stroke:#333,stroke-width:2px
    style F fill:#FFD600,stroke:#333,stroke-width:2px
    style n2 fill:#FFE0B2,stroke:#333,stroke-width:2px
    style n3 fill:#FFF9C4,stroke:#333,stroke-width:2px